#!/usr/bin/env python3
"""Splice results/paper_data.tex into paper/main.tex.

The deliverable is one self-contained file with no \\input and no external figures, so
the generated data lives literally inside it, between:

    % >>> INLINE-DATA BEGIN (generated by tools/make_paper_data.py; do not edit)
    ...
    % <<< INLINE-DATA END

Run `make paper-data` to regenerate and re-splice.
"""
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PAPER = os.path.join(ROOT, "paper", "main.tex")
DATA = os.path.join(ROOT, "results", "paper_data.tex")

BEGIN = "% >>> INLINE-DATA BEGIN (generated by tools/make_paper_data.py; do not edit)"
END = "% <<< INLINE-DATA END"


def main():
    tex = open(PAPER, encoding="utf-8").read()
    data = open(DATA, encoding="utf-8").read().rstrip("\n")
    if BEGIN not in tex or END not in tex:
        sys.exit(f"markers not found in {PAPER}; expected\n  {BEGIN}\n  {END}")
    head, rest = tex.split(BEGIN, 1)
    _, tail = rest.split(END, 1)
    out = head + BEGIN + "\n" + data + "\n" + END + tail
    with open(PAPER, "w", encoding="utf-8") as f:
        f.write(out)
    print(f"spliced {len(data.splitlines())} lines of generated data into {PAPER}")


if __name__ == "__main__":
    main()
