#!/usr/bin/env python3
"""Write DIAGNOSTICS.md: estimand gap, weight information, propensity error.

The paper says Eq. (3) targets an exponentially weighted risk on a trimmed overlap
population rather than the trailing-window risk of Section III, and that the gap is
measured rather than bounded. This is that measurement. It also answers whether the
200-unit support gate is really 200 useful observations, and how far the learned
disclosure propensity sits from the truth the simulator knows.

    python tools/make_diagnostics_report.py
"""
from __future__ import annotations
import json, os, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
R = json.load(open(os.path.join(ROOT, "results", "results.json")))
ORDER = ["M2", "M3", "M4", "M5", "M5_oracle"]
NAMES = {"M2": "M2 cost-thresh", "M3": "M3 aci-budget", "M4": "M4 aci-budget-crc",
         "M5": "M5 -iap", "M5_oracle": "M5, oracle p_d"}


def g(d, k, f="mean"):
    v = d.get(k)
    return v.get(f) if isinstance(v, dict) else v


def fmt(v, n=4):
    return "--" if v is None else (f"{v:.{n}g}" if isinstance(v, float) else str(v))


def section(stream, title):
    S = R["methods"][stream]
    L = [f"## {title}", "",
         "### Estimand gap", "",
         "`trailing` is the boxcar trailing-window risk on true labels that Section III",
         "defines as the target. `overlap` is what Eq. (3) actually targets: geometric",
         "decay, and low-propensity rows trimmed from both sums. `|gap|` is the mean",
         "absolute difference per window, `rel` the same relative to the trailing value.", "",
         "| method | trailing | overlap | mean abs gap | p90 gap | rel gap | trimmed rows | trimmed fraud |",
         "|---|---|---|---|---|---|---|---|"]
    for k in ORDER:
        if k not in S:
            continue
        d = S[k]
        L.append("| " + " | ".join([
            NAMES[k], fmt(g(d, "r_trail_mean")), fmt(g(d, "r_overlap_mean")),
            fmt(g(d, "gap_overlap_mean")), fmt(g(d, "gap_overlap_p90")),
            fmt(g(d, "gap_overlap_rel")), fmt(g(d, "trim_share_mean")),
            fmt(g(d, "trim_fraud_share_mean"))]) + " |")
    L += ["", "### Weight information", "",
          "The support gate admits a threshold once 200 units of calibration weight sit",
          "at or below it. That is not 200 observations. Kish effective sample size says",
          "how many it is worth.", "",
          "| method | ESS mean | ESS median | ESS p05 | max normalised weight | share held by top 1% |",
          "|---|---|---|---|---|---|"]
    for k in ORDER:
        if k not in S:
            continue
        d = S[k]
        L.append("| " + " | ".join([
            NAMES[k], fmt(g(d, "ess_mean")), fmt(g(d, "ess_median")),
            fmt(g(d, "ess_p05")), fmt(g(d, "w_max_norm_mean")),
            fmt(g(d, "w_top1_share_mean"))]) + " |")
    L += ["", "### Disclosure-propensity error", "",
          "Learned `p_d` against the simulator's truth, on the ledger channel. The model",
          "sees the standardised invoice amount and the frozen score. It does not see the",
          "fraud topology, which is what actually sets disclosure, so this is the error",
          "from structural unobserved heterogeneity and not only from estimation noise.", "",
          "| method | mean abs error | mean squared error | share clipped at a bound |",
          "|---|---|---|---|"]
    for k in ORDER:
        if k not in S:
            continue
        d = S[k]
        if g(d, "pd_mae_mean") is None:
            continue
        L.append("| " + " | ".join([
            NAMES[k], fmt(g(d, "pd_mae_mean")), fmt(g(d, "pd_brier_mean")),
            fmt(g(d, "pd_clip_share_mean"))]) + " |")
    return L + [""]


def main():
    out = ["# DIAGNOSTICS.md", "",
           "Generated by `tools/make_diagnostics_report.py`. Three things the paper",
           "asserted but did not show.", ""]
    out += section("synb2b", "SynB2B-Fraud-Stream")
    out += section("ulb", "ULB card portfolio")
    p = os.path.join(ROOT, "DIAGNOSTICS.md")
    open(p, "w").write("\n".join(out) + "\n")
    print("wrote", p)
    return 0


if __name__ == "__main__":
    sys.exit(main())
