#!/usr/bin/env python3
"""results/paper_data.tex - table bodies and pgfplots coordinate lists.

Four significant figures throughout. The paper is a single self-contained file, so
tools/inline_paper_data.py splices this between the INLINE-DATA markers; keeping the
generator means the numbers can be rebuilt and re-spliced rather than retyped.
"""
from __future__ import annotations

import json
import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "src"))
from t13 import config as C  # noqa: E402

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
RES = os.path.join(ROOT, "results")


def sig(x, n=4):
    if x is None:
        return "--"
    if x == 0:
        return "0"
    from math import floor, log10
    d = n - 1 - int(floor(log10(abs(x))))
    d = max(d, 0)
    return f"{round(x, d):.{d}f}"


def m(cell):
    return None if not cell else cell.get("mean")


def ci(cell, n=4):
    if not cell or cell.get("mean") is None:
        return "--"
    if cell.get("ci_lo") is None:
        return sig(cell["mean"], n)
    return f"{sig(cell['mean'], n)}"


def ci_pair(cell, n=3):
    if not cell or cell.get("ci_lo") is None:
        return "--"
    return f"[{sig(cell['ci_lo'], n)}, {sig(cell['ci_hi'], n)}]"


def coords(xs, ys, prec=6):
    return " ".join(f"({x:.{prec}g},{y:.{prec}g})"
                    for x, y in zip(xs, ys) if y is not None)


def downsample(xs, ys, k):
    if len(xs) <= k:
        return xs, ys
    step = len(xs) / k
    idx = [int(i * step) for i in range(k)]
    if idx[-1] != len(xs) - 1:
        idx.append(len(xs) - 1)
    return [xs[i] for i in idx], [ys[i] for i in idx]


def main():
    with open(os.path.join(RES, "results.json")) as f:
        R = json.load(f)
    L = []
    A = L.append
    A("% ---------------------------------------------------------------------------")
    A("% Generated by tools/make_paper_data.py from results/results.json.")
    A("% Do not hand-edit: run `make paper-data` to rebuild and re-splice.")
    A(f"% source commit {R['provenance']['git_commit']}  generated {R['provenance']['utc']}")
    A("% ---------------------------------------------------------------------------")

    S = R["methods"]["synb2b"]
    U = R["methods"]["ulb"]
    fb = R["stream_facts"]["synb2b"]
    fu = R["stream_facts"]["ulb"]
    order = ["M0", "M1", "M2", "M3", "M4", "M5_legacy", "M5",
             "M5_strictmatch", "M5_joint_static", "M5_oracle"]
    names = {"M5_legacy": r"\textbf{M5 \textsc{-iap}}",
             "M5_strictmatch": r"\quad M5, strict match",
             "M5_joint_static": r"\quad M5, joint likelihood",
             "M0": "M0 \\textsc{static}", "M1": "M1 \\textsc{conf-fixed}",
             "M2": "M2 \\textsc{cost-thresh}", "M3": "M3 \\textsc{aci-budget}",
             "M4": "M4 \\textsc{aci-budget-crc}",
             "M5": r"\quad M5, cohort-matched",
             "M5_oracle": "\\quad M5, oracle $p_d$"}

    # ---- Table I: methods on SynB2B -------------------------------------
    A("")
    A("% TABLE I body: methods on SynB2B-Fraud-Stream")
    A("\\newcommand{\\TableMethodsBody}{%")
    for k in order:
        d = S[k]
        A(f"{names[k]} & {ci(d['for_overall'])} & {ci(d['quiet_for'])} & "
          f"{ci(d['review_demand_rate'])} & {ci(d['review_served_rate'])} & "
          f"{ci(d['infeasible_rate'], 3)} & {sig(m(d['cost_per_1k']), 4)} & "
          f"{ci(d['bias_ratio_warm'], 3)} \\\\")
    A("}")

    # ---- Table II: eps ablation -----------------------------------------
    A("")
    A("% TABLE II body: exploration ablation on SynB2B-Fraud-Stream (M5)")
    A("\\newcommand{\\TableEpsBody}{%")
    for r in R["ablation"]["synb2b"]["epsilon"]:
        A(f"{sig(r['level'], 3)} & {int(round(m(r['n_explore'])))} & "
          f"{ci(r['bias_ratio_warm'], 3)} & {ci_pair(r['bias_ratio_warm'], 3)} & "
          f"{ci(r['quiet_for'])} & {ci(r['block_rate'])} & "
          f"{sig(m(r['cost_per_1k']), 4)} \\\\")
    A("}")

    # ---- Table III: ULB --------------------------------------------------
    A("")
    A("% TABLE III body: external validity, ULB card portfolio")
    A("\\newcommand{\\TableUlbBody}{%")
    for k in ["M0", "M2", "M4", "M5"]:
        d = U[k]
        A(f"{names[k]} & {ci(d['for_overall'])} & {ci(d['quiet_for'])} & "
          f"{ci(d['review_demand_rate'])} & {ci(d['review_served_rate'])} & "
          f"{ci(d['infeasible_rate'], 3)} & {sig(m(d['cost_per_1k']), 4)} & "
          f"{ci(d['bias_ratio_warm'], 3)} \\\\")
    A("}")

    # ---- Fig 3: realised risk over time ---------------------------------
    A("")
    A("% FIGURE 3: realised risk on the auto-allow path, per 2000-transaction block")
    for k, macro in (("M1", "SeriesMone"), ("M4", "SeriesMfour"), ("M5", "SeriesMfive")):
        s = S[k]["series"]
        xs, ys = downsample(s["day"], s["for"], 44)
        A(f"\\newcommand{{\\{macro}}}{{{coords(xs, ys)}}}")
    A(f"\\newcommand{{\\AlphaSynb}}{{{sig(fb['alpha'], 3)}}}")
    for i, ev in enumerate(fb["events"]):
        A(f"\\newcommand{{\\Drift{'ABC'[i]}}}{{{sig(ev['day'], 5)}}}")

    # ---- Fig 4: budget vs realised risk ---------------------------------
    A("")
    A("% FIGURE 4: review budget against realised risk (M5), with bootstrap band")
    rows = R["ablation"]["synb2b"]["budget"]
    xs = [r["level"] for r in rows]
    A("\\newcommand{\\BudgetCurve}{"
      + coords(xs, [m(r["quiet_for"]) for r in rows]) + "}")
    A("\\newcommand{\\BudgetLo}{"
      + coords(xs, [r["quiet_for"]["ci_lo"] for r in rows]) + "}")
    A("\\newcommand{\\BudgetHi}{"
      + coords(xs, [r["quiet_for"]["ci_hi"] for r in rows]) + "}")
    # closed polygon for the interval band: lo forward, hi reversed. Built here so the
    # paper needs no pgfplots fillbetween library and no named paths.
    lo = [r["quiet_for"]["ci_lo"] for r in rows]
    hi = [r["quiet_for"]["ci_hi"] for r in rows]
    A("\\newcommand{\\BudgetBand}{"
      + coords(xs + xs[::-1], lo + hi[::-1]) + "}")
    A("\\newcommand{\\BudgetOverall}{"
      + coords(xs, [m(r["for_overall"]) for r in rows]) + "}")
    A("\\newcommand{\\BudgetInfeas}{"
      + coords(xs, [m(r["infeasible_rate"]) for r in rows]) + "}")

    # ---- Fig 5: calibration composition ---------------------------------
    A("")
    A("% FIGURE 5: where the calibration weight comes from, over time (M5)")
    comp = S["M5"]["composition"]
    for field, macro in (("w_review", "CompReview"), ("w_ledger", "CompLedger"),
                         ("w_explore", "CompExplore")):
        xs, ys = downsample(comp["day"], comp[field], 60)
        A(f"\\newcommand{{\\{macro}}}{{{coords(xs, ys)}}}")

    # ---- Fig 6 data (estimator reading vs truth), used inside Fig 3 panel
    A("")
    A("% estimator reading against the truth of the same window (M4 and M5)")
    for k, macro in (("M4", "EstMfour"), ("M5", "EstMfive")):
        c = S[k]["composition"]
        xs, ys = downsample(c["day"], c["e_t"], 44)
        A(f"\\newcommand{{\\{macro}}}{{{coords(xs, ys)}}}")
    c = S["M5"]["composition"]
    xs, ys = downsample(c["day"], c["e_true"], 44)
    A(f"\\newcommand{{\\EstTrue}}{{{coords(xs, ys)}}}")

    # ---- scalar macros used in captions ---------------------------------
    A("")
    A("% scalars quoted in captions")
    A(f"\\newcommand{{\\NSeeds}}{{{len(R['seeds'])}}}")
    A(f"\\newcommand{{\\NBoot}}{{{C.BOOTSTRAP_RESAMPLES:,}}}".replace(",", "{,}"))
    A(f"\\newcommand{{\\BudgetVal}}{{{sig(R['policy_default']['budget'], 3)}}}")
    A(f"\\newcommand{{\\HoldCap}}{{{sig(R['policy_default']['block_cap'], 3)}}}")
    A(f"\\newcommand{{\\EpsDefault}}{{{sig(R['policy_default']['epsilon'], 3)}}}")
    A(f"\\newcommand{{\\AlphaUlb}}{{{sig(fu['alpha'], 3)}}}")

    out = os.path.join(RES, "paper_data.tex")
    with open(out, "w") as f:
        f.write("\n".join(L) + "\n")
    print("wrote", out, f"({len(L)} lines)")


if __name__ == "__main__":
    main()
