#!/usr/bin/env python3
"""Score the budget-infeasibility flag against oracle feasibility.

Writes INFEASIBILITY_VALIDATION.md from results/results.json. The oracle is
Proposition 1 evaluated on each window's true risk curve: (alpha, b) was attainable
exactly when the true risk at the hold-cap floor clears alpha. Windows whose true
curve has too little support at that floor are undetermined and excluded.

    python tools/make_flag_report.py
"""
from __future__ import annotations
import json, os, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
R = json.load(open(os.path.join(ROOT, "results", "results.json")))
ORDER = ["M0", "M1", "M2", "M3", "M4", "M5", "M5_oracle"]
NAMES = {"M0": "M0 static", "M1": "M1 conf-fixed", "M2": "M2 cost-thresh",
         "M3": "M3 aci-budget", "M4": "M4 aci-budget-crc", "M5": "M5 -iap",
         "M5_oracle": "M5, oracle p_d"}


def g(d, k, f="mean"):
    v = d.get(k)
    if isinstance(v, dict):
        return v.get(f)
    return v


def fmt(v, n=3):
    if v is None:
        return "--"
    if isinstance(v, float):
        return f"{v:.{n}f}"
    return str(v)


def table(stream):
    S = R["methods"][stream]
    L = ["| method | flag rate | oracle rate | precision | recall | specificity | bal. acc | missed | false alarm | windows |",
         "|---|---|---|---|---|---|---|---|---|---|"]
    for k in ORDER:
        if k not in S:
            continue
        d = S[k]
        n = g(d, "flag_n_scored")
        if not n:
            L.append(f"| {NAMES[k]} | {fmt(g(d,'infeasible_rate'))} | -- | -- | -- | -- | -- | -- | -- | 0 |")
            continue
        L.append("| " + " | ".join([
            NAMES[k], fmt(g(d, "infeasible_rate")), fmt(g(d, "oracle_infeasible_rate")),
            fmt(g(d, "flag_precision")), fmt(g(d, "flag_recall")),
            fmt(g(d, "flag_specificity")), fmt(g(d, "flag_balanced_acc")),
            fmt(g(d, "flag_missed_infeasible_rate")),
            fmt(g(d, "flag_false_infeasible_rate")), fmt(n, 0)]) + " |")
    return L


def risk_table(stream):
    S = R["methods"][stream]
    L = ["| method | true risk, flag on | true risk, flag off | delay: covariate | concept | prior |",
         "|---|---|---|---|---|---|"]
    for k in ORDER:
        if k not in S or not g(S[k], "flag_n_scored"):
            continue
        d = S[k]
        L.append("| " + " | ".join([
            NAMES[k], fmt(g(d, "risk_when_flagged"), 5), fmt(g(d, "risk_when_not_flagged"), 5),
            fmt(g(d, "flag_delay_covariate"), 1), fmt(g(d, "flag_delay_concept"), 1),
            fmt(g(d, "flag_delay_prior"), 1)]) + " |")
    return L


def main():
    out = [
        "# INFEASIBILITY_VALIDATION.md", "",
        "Generated by `tools/make_flag_report.py`.", "",
        "The paper calls the budget-infeasibility flag a deliverable of the method. Until",
        "now it reported only how often the flag fires, which says nothing about whether it",
        "fires when it should. This scores it against oracle feasibility.", "",
        "**Oracle.** Proposition 1 on the window's true risk curve: with",
        "`q = 1 - beta - b(1-eps)`, the pair `(alpha, b)` was attainable exactly when the",
        "true risk at `F^-1(q)` clears `alpha`. The true curve uses latent `y` on every",
        "decision in the window, decay-weighted like the estimator but with no propensity",
        "weighting and no trimming. It is computed read-only: `tests/test_flag_validation.py`",
        "stubs the scorer and asserts every policy metric is unchanged.", "",
        "Windows with less than `min_support` true weight at the floor are **undetermined**",
        "and excluded rather than guessed at. M0 and M1 never update, so they have no",
        "windows to score; their flag rate of 0 is the absence of a mechanism, not a result.",
        "", "## SynB2B-Fraud-Stream", "",
    ]
    out += table("synb2b")
    out += ["", "True release-region risk in flagged vs unflagged windows, and how long after",
            "each drift event the flag caught up with the oracle (days):", ""]
    out += risk_table("synb2b")
    out += ["", "## ULB card portfolio", ""]
    out += table("ulb")
    out += [""]
    out += risk_table("ulb")
    out += ["", "## Reading", "",
            "Precision is the share of flagged windows that were genuinely infeasible;",
            "recall is the share of genuinely infeasible windows that were flagged.",
            "A method that flags everything scores high recall and near-zero specificity,",
            "which is what a permanently-on warning light looks like.", ""]
    p = os.path.join(ROOT, "INFEASIBILITY_VALIDATION.md")
    open(p, "w").write("\n".join(out) + "\n")
    print("wrote", p)
    return 0


if __name__ == "__main__":
    sys.exit(main())
